---
version: "3.1"

services:

  app:
    image: metti-service:local
    build:
      context: '.'
      dockerfile: docker/app/local.dockerfile
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - .:/srv

  database:
    image: mariadb:10.3
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_USER=${DATABASE_USERNAME}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
    ports:
      - "127.0.0.1:3305:3306"
    volumes:
      - database:/var/lib/mysql
    env_file:
      - ./.env

  memcached:
    image: memcached:1.5

volumes:

  database:
    driver: local
