version: '3.8'

services:
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn metti.main:app --reload --host 0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 3911:8000
    environment:
      - DATABASE_URL=postgresql://metti:m3tt1337@db:5432/metti
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=metti
      - POSTGRES_PASSWORD=m3tt1337
      - POSTGRES_DB=metti
volumes:
  postgres_data: